services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"  # Expose the Nginx port
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app-network

  apigateway:
    container_name: apigateway
    build:
      context: .
      dockerfile: Dockerfile.apigateway
    ports:
      - "8000:8000"
    volumes:
      - ./apigateway:/app/apigateway
    networks:
      - app-network
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=ssouser
      - KC_DB_PASSWORD=ssopass
      - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev

  # PostgreSQL database
  postgres:
    image: postgres:16.6
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=keycloak              # Default database for Keycloak
    ports:
      - "5432:5432"                       # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge
  
volumes:
  postgres_data:
